// fetch products
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'
export const AJAX_PRODUCTS = 'AJAX_PRODUCTS'

// fetch product detail and update isLiked
export const FETCH_DETAIL_REQUEST = 'FETCH_DETAIL_REQUEST'
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS'
export const UPDATE_DETAIL = 'UPDATE_DETAIL'
export const FETCH_DETAIL_FAIL = 'FETCH_DETAIL_FAIL'

// wishlist
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST'
